// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaRMNaElExrKm0syjnCLf_1b69B1-YcuU',
    appId: '1:14364658100:web:06ea360ac5caf8f5d08ae1',
    messagingSenderId: '14364658100',
    projectId: 'heimwatt-staging',
    authDomain: 'heimwatt-staging.firebaseapp.com',
    storageBucket: 'heimwatt-staging.firebasestorage.app',
    measurementId: 'G-BCMT742E7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg-c_HCIdXaBwpvIq3OwaYHSKGtTVoQhc',
    appId: '1:14364658100:android:1f015b1b5d2d02b8d08ae1',
    messagingSenderId: '14364658100',
    projectId: 'heimwatt-staging',
    storageBucket: 'heimwatt-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhQnyx41GLYLKszcQ6dVvt9fOroU-K__I',
    appId: '1:14364658100:ios:31bb13f651bf9d66d08ae1',
    messagingSenderId: '14364658100',
    projectId: 'heimwatt-staging',
    storageBucket: 'heimwatt-staging.firebasestorage.app',
    iosBundleId: 'com.app.heimwatt',
  );

}